### ISSUE TITLE
Can't set Steam username in User CP or Admin CP

### ISSUE THREAD

**Issue by ghost** [Tanweth/MySteam-Powered#1]
I've installed the mod in my forum:
http://loliworld.net/foros/index.php

I can set the Advanced-Sidebox and the Steam section with Steam API activated, but now i cant see the link for Steam username settings in my user CP or Admin CP. Maybe i must edit some files but i'm a noob in myBB.

**Comment by Tanweth** [comment]
I'm not sure what you mean by Steam username settings. Do you mean the area for integrating your Steam account? If so, there should be a section on your User CP called "Steam Integration" (take a look at this screenshot for where it is and what it looks like: http://kerfufflealliance.com/pictures/mysteam/mysteam_usercp_nav.jpg ). If you don't see that, have you entered certain groups in "Limit Usergroups Displayed?" in the Admin CP? If so, make sure you're in one of the usergroups that you listed there (you won't see the form on the User CP if you're not in one of the allowed groups). Even if you're an administrator, you wouldn't see it unless you're a member of one of the groups listed.

This form integrates Steam for yourself. If you want to integrate Steam for a user other than yourself, you can do that in the Moderator CP. Go to Profile Editor, select a user, then find the form at the bottom (below the usual MyBB stuff). There's no Admin CP form for doing that at this time at least.

Let me know if I've misunderstood you or you still aren't seeing it.

**Comment by ghost** [comment]
I'm in an allowed group.
The mod says "Changes take effect on the next cache refresh.", maybe thats the problem, i will wait for tomorrow... Is there any way to refresh the cache manually?
Thanks ;)

**Comment by Tanweth** [comment]
The cache is by default refreshed every 10 minutes, so that wouldn't be it. And if you want to refresh the cache manually, the way to do that currently is to set the Cache Lifespan setting to 0, refresh a forum page that is modified by the plugin (e.g. a page that the status list appears on), then set it back to 10 (or whatever setting you'd like). Though that gives me an idea: I should add a link to refresh the cache next to every setting that requires a cache refresh. That would be easy to do. Anyway, the limit by group setting would actually take effect immediately with regard to the visibility of the User CP form, if that's what you mean.

Let's start with some basic troubleshooting questions:
1. What setting changes have you made?
2. Is the User CP form visible to you if you don't enter any groups in the "Limit Usergroups Displayed?" setting?
3. Is the form in the Moderator CP Profile Editor visible?
4. What happens if you try to access the User CP page directly? You can do that by typing the following in the address bar of your browser: (your forum's URL)/usercp.php?action=steamid.

**Comment by ghost** [comment]
1- I've only changed a few settings, look at the screenshot:
http://s27.postimg.org/3woga0c6r/Captura_de_pantalla_de_2014_03_08_11_26_28.png
2- The User CP form isn't visible with no groups entered.
3- I can't see the form in the Moderator CP or the Administrator CP.
4- I get a blank page.

**Comment by Tanweth** [comment]
In that case, check if there are any templates created for the theme you're using. Go to Admin CP > Templates & Styles > (whatever template set is being used by your theme). See if there's a template group called "MySteam Powered Templates." If it's there, there should be 10 templates listed in that group.

If it was a permissions issue, on the fourth one you would've seen a "no permissions" page rather than just a blank page. A blank page means it isn't reading the template.

**Comment by ghost** [comment]
On the fourth template i can see this:
![mysteam](https://f.cloud.github.com/assets/6887384/2366326/8f04ad36-a6fc-11e3-99b9-598e98442064.png)

**Comment by Tanweth** [comment]
That's correct. I assume that means that the templates are generated? Is that the only template that has any content?

**Comment by ghost** [comment]
All the templates have the content... :/

**Comment by Tanweth** [comment]
Well this one has me baffled I'll admit. Let me take another look at the code and see if I can get any inspiration as to what may be causing it, then I'll get back to you.

**Comment by ghost** [comment]
Thank you, ask me anything you want, i can do the betatesting :D

**Comment by Tanweth** [comment]
One thing that occurred to me on another view of this is that a template from this plugin is definitely being read, but it's from the ASB module (based on the screenshot you posted). The templates used by the ASB module are generated through ASB's unique system for handling modules, so that may be significant.

But first we should make sure that it really is that your forum can't read any of the templates from the main plugin. Can you try enabling the non-ASB status list in the plugin's settings? You don't need to delete the ASB module or do anything with it, they can co-exist. Once that's enabled, if everything works as it is supposed to, you should see a section above your forums (on the forum index page) for the status list. Since you don't have any users, it will display the same error message that the ASB sidebox does. If you enable it and don't see anything (and you haven't displayed "Display Status List on Index?" under the "MySteam Powered Status List (Non-Advanced Sidebox)" settings group), that means that it isn't able to read that template either, and it will indicate that none of the plugin's templates are able to be read. Either way, it gives me an indicator of what to check.

**Comment by ghost** [comment]
I have tested the non-Advanced Sidebox and it doesn't work, i guess the templates cannot be readed :/
I've tested that in default theme and other themes, no one works.

**Comment by Tanweth** [comment]
A poster on the MyBB release thread also apparently has the same issue. I'll ask you the same questions I asked him, just in-case they end up being significant: Could you tell me what your current MyBB version is? Your current PHP version (it's displayed in the debug text at the bottom of every page on your forum, if you're logged into an admin account)? Do you have any other plugins installed (and if so, what are they?)? Have you experienced this issue with any other plugins before?

**Comment by ghost** [comment]
MyBB version: 1.6.12
PHP version: 5.3.28
Installed plugins:
- Akismet 1.2.2
- Advanced Sidebox 2.0.3
- Rate Me a Funny 1.2.5

I never experimented somthing like this with other plugins, my forum has 2 weeks of life, i've only installed the plugins above and tried to install "Fit on Page 2.1" but didn't work.

**Comment by Tanweth** [comment]
Thanks for the info. Probably not a MyBB version issue or PHP issue. The other user has a ton of plugins, but since you only have three that makes it being a plugin conflict unlikely. It also makes it that much more baffling as to why you experience the issue but I (and presumably most other users) don't. But anyway, I'll keep looking and get back to you.

**Comment by Tanweth** [comment]
I did have a thought as to the possible issue, but since I can't reproduce it I can't test it. I uploaded a package with the test change to this post on the release thread (http://community.mybb.com/thread-151564-post-1065707.html#pid1065707). Try uploading the new files to your forums. No need to deactivate and reactivate the plugin. Let me know if anything changes.

**Comment by ghost** [comment]
I just updated the files but the form didn't appeared. :(

**Comment by Tanweth** [comment]
Well the good news is, I just tried installing the plugin to a fresh install of MyBB, and that install is experiencing your issue. I haven't fixed it yet, but now I can reproduce it and test changes directly. I'll get back to you when I figure it out.

**Comment by Tanweth** [comment]
Alright, now that I could reproduce the issue, I was able to fix it. It was a simple oversight on my part. Give v1.0.2 a download and let me know if you encounter any further issue. :smile:
