### ISSUE TITLE
Origin

### ISSUE THREAD

**Issue by dthiago** [Tanweth/MySteam-Powered#10]
Can u integrate EA Origin too?
Cause there´s a lot of players playing BF4,BF3 and others games.

**Comment by Tanweth** [comment]
EA doesn't expose an Origin web API like Steam does, unfortunately. I can see the attraction in doing that, especially since the Steam Web API no longer detects non-Steam games, bafflingly (it used to until a few months ago), but without an API that allows me to contact a server and get info on an Origin user, there's no way I can integrate it.

**Comment by dthiago** [comment]
OK. I understand it . 
But if you still interested in mybb with gametools like this http://bf4db.com/players/27216 . 
IF Mybb default profile can be integrated with these kind of database.
You can see API here http://bf4stats.com/api

**Comment by Tanweth** [comment]
That API only gives general stats, it doesn't give a user's current in-game status as far as I can see. In addition, every API added on increases the server load and code complexity, plus increases the scope of the plugin. My goal is to provide a robust suite of Steam integration features, and not really go beyond that. Certainly integrating something as specific as a Battlefield 4 stats API is too idiosyncratic for a plugin like this. I would consider developing a customized version for you for a fee, but that's it. Thanks for the suggestion all the same. :smile:
