### ISSUE TITLE
User Profile View Error

### ISSUE THREAD

**Issue by andydigi** [Tanweth/MySteam-Powered#3]
OK sometimes after adding a user's steam details when you go to view their profile you get a blank page and the following error code:-

Fatal error: Unsupported operand types in inc/plugins/mysteam.php on line 1291
(I've removed part of the file structure). Hope this helps

**Comment by Tanweth** [comment]
I'm pretty sure I know what's causing that, and if I do, then I've already fixed it in the latest development build (not uploaded yet). I'll keep this issue open for now, since it can be difficult to pinpoint and I therefore can't test it thoroughly myself. Once I release the update, just let me know if the issue crops up again. Thanks for your report. :)

**Comment by andydigi** [comment]
Glad to help! It's a great plugin.

**Comment by Tanweth** [comment]
I'm going to go ahead and close this issue, since that particular warning should be fixed now (though there may be new warnings, and indeed I discovered one through using this on my website: #6 ). If you do encounter it or another warning again, let me know. :smile:
