### ISSUE TITLE
There is not spanish support........

### ISSUE THREAD

**Issue by ghost** [Tanweth/MySteam-Powered#4]
... but you can use this:
https://mega.co.nz/#!jYd00KJC!qmkiUeTiaXd6taK0Jkz5FRfjwPQXlTydgWR7ES7mqg4

I've translated the mod, use the translation freely. ;)

**Comment by Tanweth** [comment]
Thanks for that. I'll take a quick look at it and see about including it in the next version (with credit to you, of course). :)

**Comment by ghost** [comment]
You're welcome, your mod is awesome ;D

**Comment by Tanweth** [comment]
I took a look at the language file, and it looks like some of the settings entries have yet to be translated. Is the translation still a WIP?

**Comment by ghost** [comment]
I'm sorry, i forget that lines :(

Here is the completed translation: https://mega.co.nz/#!zINX2KBA!I_x2Y0uH54Si3ZwmjeyoN_vh-BdSDM0ty-d8OczShMc

**Comment by Tanweth** [comment]
Awesome! Once again I appreciate your work, especially considering that you currently can't use this plugin since you're experiencing a critical issue. What I would suggest you do is submit the language pack to the MyBB Mods site. That way the language pack will show up on the downloads page for MySteam Powered there, and you will have control over it so you can update it yourself when needed. Including it in the main package could get awkward if I add to the default English language file before you've had a chance to update your language pack. Once it's submitted and validated, I'll announce it in the readme (with credit to you) and the release thread, and point readers to the MyBB Mods download link.

You can submit it here: http://mods.mybb.com/submit (select Language Pack from the submission type). You'll need to register an account there if you haven't already.

**Comment by ghost** [comment]
I've uploaded the translation to the MyBB mod page, it will be validated in 24 hours or less, thanks for the tip :D
